In [1]:
import pandas as pd

In [2]:
people = {
    "First" : ['Himanshu','Rahul','Shyam'],
    "Last"  : ['Kumar','Saini','Singh'],
    "Email" : ['HimanshuKumar@gmail.com','RahulSaini@gmail.com','ShyamSingh@gmail.com']
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

      First   Last                    Email
0  Himanshu  Kumar  HimanshuKumar@gmail.com
1     Rahul  Saini     RahulSaini@gmail.com
2     Shyam  Singh     ShyamSingh@gmail.com

In [6]:
df.set_index("Email")

                            First   Last
Email
HimanshuKumar@gmail.com  Himanshu  Kumar
RahulSaini@gmail.com        Rahul  Saini
ShyamSingh@gmail.com        Shyam  Singh

In [7]:
df

      First   Last                    Email
0  Himanshu  Kumar  HimanshuKumar@gmail.com
1     Rahul  Saini     RahulSaini@gmail.com
2     Shyam  Singh     ShyamSingh@gmail.com

for Permanent replacement

In [8]:
df.set_index('Email',inplace=True)

In [9]:
df

                            First   Last
Email
HimanshuKumar@gmail.com  Himanshu  Kumar
RahulSaini@gmail.com        Rahul  Saini
ShyamSingh@gmail.com        Shyam  Singh

In [10]:
df.index

Index(['HimanshuKumar@gmail.com', 'RahulSaini@gmail.com',
       'ShyamSingh@gmail.com'],
      dtype='object', name='Email')

For reseting the indexes

In [11]:
df.reset_index(inplace=True)

In [12]:
df

                     Email     First   Last
0  HimanshuKumar@gmail.com  Himanshu  Kumar
1     RahulSaini@gmail.com     Rahul  Saini
2     ShyamSingh@gmail.com     Shyam  Singh

For setting up index during reading of a csv file

In [13]:
newDf = pd.read_csv('CSV/survey_results_public.csv',index_col='ResponseId')

In [16]:
newDf.head(3)

,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0

In [21]:
schema_df = pd.read_csv('CSV/survey_results_schema.csv',index_col='qname')

In [30]:
schema_df.head()

,qid,question,force_resp,type,selector
qname,,,,,
AIAcc,QID324,For the AI tools you use as part of your devel...,False,MC,MAVR
AIBen,QID316,How much do you trust the accuracy of the outp...,False,MC,SAVR
AIDev,QID328,Which <b>AI-powered developer tools</b> did yo...,False,Matrix,Likert
AINext,QID320,Thinking about how your workflow and process c...,False,Matrix,Likert
AIOpen,QID321,Please describe how you would expect your work...,False,TE,SL

In [28]:
schema_df.sort_index(inplace=True)