In [1]:
people = {
    "First" : ['Himanshu','Rahul','Shyam'],
    "Last"  : ['Kumar','Saini','Singh'],
    "Email" : ['HimanshuKumar@gmail.com','RahulSaini@gmail.com','ShyamSingh@gmail.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

      First   Last                    Email
0  Himanshu  Kumar  HimanshuKumar@gmail.com
1     Rahul  Saini     RahulSaini@gmail.com
2     Shyam  Singh     ShyamSingh@gmail.com

In [5]:
df.columns

Index(['First', 'Last', 'Email'], dtype='object')

To change all of the Names of the Columns

In [6]:
df.columns = ['First_name','Last_Name','Emails']

In [7]:
df

  First_name Last_Name                   Emails
0   Himanshu     Kumar  HimanshuKumar@gmail.com
1      Rahul     Saini     RahulSaini@gmail.com
2      Shyam     Singh     ShyamSingh@gmail.com

for changes all of the columns but using a list comprehension

In [8]:
df.columns = [x.upper() for x in df.columns]

In [9]:
df

  FIRST_NAME LAST_NAME                   EMAILS
0   Himanshu     Kumar  HimanshuKumar@gmail.com
1      Rahul     Saini     RahulSaini@gmail.com
2      Shyam     Singh     ShyamSingh@gmail.com

for removing space with underscore or vise verse

In [10]:
df.columns = df.columns.str.replace('_',' ')

In [11]:
df

  FIRST NAME LAST NAME                   EMAILS
0   Himanshu     Kumar  HimanshuKumar@gmail.com
1      Rahul     Saini     RahulSaini@gmail.com
2      Shyam     Singh     ShyamSingh@gmail.com

when we want to change only certain columns we will use

In [12]:
df.rename(columns={'FIRST NAME' : 'first','LAST NAME': 'last'},inplace=True)

In [13]:
df

      first   last                   EMAILS
0  Himanshu  Kumar  HimanshuKumar@gmail.com
1     Rahul  Saini     RahulSaini@gmail.com
2     Shyam  Singh     ShyamSingh@gmail.com

For altering the rows

In [14]:
df.loc[0] = ['Himanshu','Prajapati','HimanshuPrajapati@gmail.com']

In [15]:
df

      first       last                       EMAILS
0  Himanshu  Prajapati  HimanshuPrajapati@gmail.com
1     Rahul      Saini         RahulSaini@gmail.com
2     Shyam      Singh         ShyamSingh@gmail.com

if i wanted to only change a row column specific values

In [16]:
df.loc[0,'first'] = "Honey"

In [17]:
df

   first       last                       EMAILS
0  Honey  Prajapati  HimanshuPrajapati@gmail.com
1  Rahul      Saini         RahulSaini@gmail.com
2  Shyam      Singh         ShyamSingh@gmail.com

In [18]:
df['EMAILS'] = df['EMAILS'].str.lower()

In [19]:
df

   first       last                       EMAILS
0  Honey  Prajapati  himanshuprajapati@gmail.com
1  Rahul      Saini         rahulsaini@gmail.com
2  Shyam      Singh         shyamsingh@gmail.com

Four methods to Do the above action more powerful way
1. apply
2. applymap
3. Map

In [20]:
def update_emails(emails):
    return emails.upper()

In [21]:
df.columns = df.columns.str.lower()

In [22]:
df['emails']=df['emails'].apply(update_emails)

In [23]:
df

   first       last                       emails
0  Honey  Prajapati  HIMANSHUPRAJAPATI@GMAIL.COM
1  Rahul      Saini         RAHULSAINI@GMAIL.COM
2  Shyam      Singh         SHYAMSINGH@GMAIL.COM

In [24]:
# df['emails'] = [x.lower() for x in df.emails]
df['emails'] = df['emails'].apply(lambda x : x.upper())

In [25]:
df

   first       last                       emails
0  Honey  Prajapati  HIMANSHUPRAJAPATI@GMAIL.COM
1  Rahul      Saini         RAHULSAINI@GMAIL.COM
2  Shyam      Singh         SHYAMSINGH@GMAIL.COM

In [26]:
df['emails'].apply(len)

0    27
1    20
2    20
Name: emails, dtype: int64

In [27]:
df.apply(len)

first     3
last      3
emails    3
dtype: int64

In [28]:
df.apply(len,axis='columns')

0    3
1    3
2    3
dtype: int64

In [29]:
df.apply(pd.Series.min)

first                           Honey
last                        Prajapati
emails    HIMANSHUPRAJAPATI@GMAIL.COM
dtype: object

In [30]:
# df.apply(lambda x : print(x))

In [31]:
df.applymap(len)

C:\Users\hp\AppData\Local\Temp\ipykernel_9024\1485728669.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   first  last  emails
0      5     9      27
1      5     5      20
2      5     5      20

In [32]:
# for converting complete df to lower or upper case 
df.applymap(str.lower)

C:\Users\hp\AppData\Local\Temp\ipykernel_9024\78162888.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(str.lower)

   first       last                       emails
0  honey  prajapati  himanshuprajapati@gmail.com
1  rahul      saini         rahulsaini@gmail.com
2  shyam      singh         shyamsingh@gmail.com

In [33]:
df['first'].map({'Honey':'Himanshu','Rahul':'rashmi'})

0    Himanshu
1      rashmi
2         NaN
Name: first, dtype: object

In [34]:
df

   first       last                       emails
0  Honey  Prajapati  HIMANSHUPRAJAPATI@GMAIL.COM
1  Rahul      Saini         RAHULSAINI@GMAIL.COM
2  Shyam      Singh         SHYAMSINGH@GMAIL.COM

In [35]:
df['first'].replace({'Honey':'Himanshu','Rahul':'rashmi'})

0    Himanshu
1      rashmi
2       Shyam
Name: first, dtype: object

In [36]:
df['first'] =df['first'].replace({'Honey':'Himanshu','Rahul':'rashmi'})

In [37]:
df

      first       last                       emails
0  Himanshu  Prajapati  HIMANSHUPRAJAPATI@GMAIL.COM
1    rashmi      Saini         RAHULSAINI@GMAIL.COM
2     Shyam      Singh         SHYAMSINGH@GMAIL.COM

In [38]:
len(df.iloc[0])

3

In [39]:
list(df.shape)

[3, 3]

In [41]:
df_stack = pd.read_csv('CSV/survey_results_public.csv')

In [45]:
df_stack.head(3)

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,285000.0,HTML/CSS;JavaScript;Python,Bash/Shell (all shells);C#;Dart;Elixir;GDScrip...,Supabase,Firebase Realtime Database;Supabase,Amazon Web Services (AWS);Netlify;Vercel,Fly.io;Netlify;Render,Next.js;React;Remix;Vue.js,Deno;Elm;Nuxt.js;React;Svelte;Vue.js,Electron;React Native;Tauri,Capacitor;Electron;Tauri;Uno Platform;Xamarin,Docker;Kubernetes;npm;Pip;Vite;Webpack;Yarn,Godot;npm;pnpm;Unity 3D;Unreal Engine;Vite;Web...,Vim;Visual Studio Code,Vim;Visual Studio Code,iOS;iPadOS;MacOS;Windows;Windows Subsystem for...,MacOS;Windows;Windows Subsystem for Linux (WSL),Asana;Basecamp;GitHub Discussions;Jira;Linear;...,GitHub Discussions;Linear;Notion;Trello,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord;Signal;Slack;Zoom,ChatGPT,ChatGPT;Neeva AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely","I don't think it's super necessary, but I thin...",Yes,Indifferent,Other (please explain),Somewhat distrust,Learning about a codebase;Writing code;Debuggi...,Writing code;Committing and reviewing code,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,10.0,Strongly agree,Agree,Strongly agree,Agree,Agree,Agree,Agree,Strongly agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,27,23,"Developer, back-end","5,000 to 9,999 employees",I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,250000.0,Bash/Shell (all shells);Go,Haskell;OCaml;Rust,NaN,NaN,Amazon Web Services (AWS);Google Cloud;OpenSta...,NaN,NaN,NaN,NaN,NaN,Cargo;Docker;Kubernetes;Make;Nix,Cargo;Kubernetes;Nix,Emacs;Helix,Emacs;Helix,MacOS;Other Linux-based,MacOS;Other Linux-based,Markdown File;Stack Overflow for Teams,Markdown File,Microsoft Teams;Slack;Zoom,Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,23.0,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Agree,Agree,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0

In [44]:
pd.set_option('display.max_columns',85)

In [47]:
df_stack.rename(columns={'CompTotal':'Salary'},inplace=True)

In [51]:
df_stack.Salary.dropna().head()

1     285000.0
2     250000.0
3     156000.0
4    1320000.0
5      78000.0
Name: Salary, dtype: float64

In [53]:
df_stack['Q120'].value_counts()

Q120
I agree    89184
Name: count, dtype: int64

In [58]:
df_stack['SOAccount'].value_counts()

SOAccount
Yes                        66282
No                         14618
Not sure/can't remember     6952
Name: count, dtype: int64

In [64]:
df_stack['SOAccount'].map({'Yes':True,'No':False})

0          NaN
1         True
2         True
3         True
4        False
         ...
89179     True
89180     True
89181      NaN
89182    False
89183     True
Name: SOAccount, Length: 89184, dtype: object

In [65]:
df_stack['SOAccount'] =df_stack['SOAccount'].map({'Yes':True,'No':False})

In [75]:
import numpy as nd

In [77]:
df_stack.loc[(df_stack['SOAccount']==nd.nan),'SOAccount']

Series([], Name: SOAccount, dtype: object)