In [1]:
import pandas as pd

In [2]:
people = {
    "First" : ['Himanshu','Abdul','Rahul','Shyam'],
    "Last"  : ['Kumar','Khan','Kumar','Kumar'],
    "Email" : ['HimanshuKumar@gmail.com','AbdulKhan@gmail.com','RahulSaini@gmail.com','ShyamSingh@gmail.com']
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

      First   Last                    Email
0  Himanshu  Kumar  HimanshuKumar@gmail.com
1     Abdul   Khan      AbdulKhan@gmail.com
2     Rahul  Kumar     RahulSaini@gmail.com
3     Shyam  Kumar     ShyamSingh@gmail.com

In [5]:
df.sort_values(by='First',ascending=False)

      First   Last                    Email
3     Shyam  Kumar     ShyamSingh@gmail.com
2     Rahul  Kumar     RahulSaini@gmail.com
0  Himanshu  Kumar  HimanshuKumar@gmail.com
1     Abdul   Khan      AbdulKhan@gmail.com

In [6]:
df.sort_values(by=['Last','First'],ascending=[False,True],inplace=True)

In [7]:
df

      First   Last                    Email
0  Himanshu  Kumar  HimanshuKumar@gmail.com
2     Rahul  Kumar     RahulSaini@gmail.com
3     Shyam  Kumar     ShyamSingh@gmail.com
1     Abdul   Khan      AbdulKhan@gmail.com

In [8]:
df.sort_index()

      First   Last                    Email
0  Himanshu  Kumar  HimanshuKumar@gmail.com
1     Abdul   Khan      AbdulKhan@gmail.com
2     Rahul  Kumar     RahulSaini@gmail.com
3     Shyam  Kumar     ShyamSingh@gmail.com

In [9]:
df_survey = pd.read_csv('CSV/survey_results_public.csv')

In [10]:
df_survey.head(5)

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0

In [11]:
pd.set_option('display.max_columns',85)
pd.set_option('display.max_rows',85)

In [12]:
df_survey.sort_values(by=['Country','CompTotal'],inplace=True)

In [13]:
df_survey[['Country','CompTotal']].head(20).dropna()

           Country    CompTotal
59005  Afghanistan          0.0
67793  Afghanistan          0.0
61075  Afghanistan          1.0
2641   Afghanistan        123.0
37955  Afghanistan       3600.0
39426  Afghanistan       4200.0
41678  Afghanistan      56666.0
86038  Afghanistan      68000.0
53321  Afghanistan      69420.0
36048  Afghanistan      80000.0
17872  Afghanistan     100000.0
57361  Afghanistan     200000.0
1334   Afghanistan     210000.0
88347  Afghanistan  932464379.0

In [14]:
df_survey.nlargest(5,'CompTotal')

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
56322,56323,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Hobby;Contribute to open-source projects;Boots...,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Other (please specify):,NaN,NaN,More than 50 years,More than 50 years,Blockchain,"10,000 or more employees",I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Bahamas,AED United Arab Emirates dirham,5.000000e+46,Ada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,Not sure/can't remember,NaN,"No, not at all",SEX,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
18463,18464,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,NaN,NaN,11,8,"Developer, back-end",20 to 99 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,"Iran, Islamic Republic of...",IRR\tIranian rial,1.000000e+21,Bash/Shell (all shells);Python,Bash/Shell (all shells);Go;JavaScript;Python,PostgreSQL;Redis,Elasticsearch;MongoDB;PostgreSQL;Redis,Amazon Web Services (AWS),Amazon Web Services (AWS);Google Cloud,FastAPI,FastAPI,NaN,NaN,Composer;Docker,Composer;Docker,IPython;PyCharm;Vim,IPython;PyCharm;Vim,Ubuntu,Ubuntu,Jira;Trello,Jira;Trello,Discord;Google Meet;Jitsi;Skype;Slack;Telegram...,Discord;Google Meet;Skype;Telegram;Whatsapp,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per week,"Yes, somewhat",NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,11.0,Strongly agree,Neither agree nor disagree,Agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Strongly agree,Never,6-10 times a week,NaN,30-60 minutes a day,30-60 minutes a day,Microservices;Continuous integration (CI) and ...,NaN,Appropriate in length,Easy,NaN
43556,43557,I agree,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Pluralsight,8,4,"Developer, desktop or enterprise applications",500 to 999 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,Romania,RON\tRomanian leu,1.000000e+16,Assembly;Bash/Shell (all shells);C;C#;C++;F#;J...,Assembly;Bash/Shell (all shells);C;C#;C++;F#;J...,BigQuery;Cosmos DB;Elasticsearch;MariaDB;Micro...,NaN,Amazon Web Services (AWS);Microsoft Azure;VMware,Microsoft Azure;VMware,ASP.NET;ASP.NET CORE,NaN,.NET (5+) ;GTK;MFC;Opencv;OpenGL;Qt,GTK;MFC;Opencv;OpenGL;Qt,Ant;APT;Boost.Test;CMake;cppunit;Dagger;Docker...,Boost.Test;CMake;cppunit;GNU GCC;LLVM's Clang;...,Atom;Code::Blocks;Kate;Nano;Notepad++;Qt Creat...,Kate;Qt Creator;Visual Studio,Cygwin;Ubuntu;Windows,Ubuntu,GitHub Discussions;Markdown File,GitHub Discussions,IRC;Microsoft Teams;Skype,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,Less than once per month or monthly,Yes,Less than once per month or monthly,Neutral,don't,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
49553,49554,I agree,"I am not primarily a developer, but I write co...",25-34 years old,"Employed, full-time",In-person,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,22,5,Research & Development role,"1,000 to 4,999 employees",I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,1.000000e+16,Bash/Shell (all shells);C;C++;Fortran;Julia;MA...,Bash/Shell (all shells);C;C++;Fortran;Julia;MA...,NaN,NaN,NaN,NaN,NaN,NaN,NumPy;Pandas,CUDA;GTK;NumPy;Pandas;Qt;Scikit-Learn;TensorFl...,CMake;Docker;Make;MSVC;Ninja;Pip,CMake;LLVM's Clang;Make;Pip,Notepad++;Spyder;Vim;Visual Studio Code,Notepad++;Spyder;Vim;Visual Studio Code,Debian;Windows,Red Hat;Windows,Markdown File;Redmine,Markdown File;Redmine,Microsoft Teams,Microsoft Teams,WolframAlpha,ChatGPT;Google Bard AI;WolframAlpha,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"No, not really",It would be most helpful if the AI could delet...,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,11.0,Agree,Agree,Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,Agree,1-2 times a week,3-5 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Automated testing;Continuous i...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN
35779,35780,I agree,I am a developer by profession,25-34 years old,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Codecademy;Udemy;Pluralsight;Coursera;Udacity,10,7,NaN,20 to 99 employees,I have a great deal of influence,Investigate,Ask developers I know/work with;Visit develope...,Canada,CAD\tCanadian dollar,1.000000e+15,Assembly;Bash/Shell (all shells);C#;C++;Cobol;...,HTML/CSS;SQL;TypeScript,Cloud Firestore;Elasticsearch;MariaDB;Microsof...,MariaDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Cloudflare;Digital O...,NaN,Angular;AngularJS;ASP.NET;ASP.NET CORE;Deno;Ex...,Angular;NestJS,Electron,NaN,Chocolatey;CMake;Composer;Docker;Gradle;npm;We...,Docker;npm,Android Studio;Atom;Eclipse;Goland;IntelliJ ID...,Visual Studio Code,Android;Ubuntu;Windows;Windows Subsystem for L...,Android;Red Hat;Ubuntu;Windows;Windows Subsyst...,Azure Devops;Confluence;Jira;Markdown File;Trello,NaN,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord,ChatGPT,NaN,GitHub Copilot,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,none,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [15]:
df_survey.fillna()

ValueError: Must specify a fill 'value' or 'method'.