In [38]:
import pandas as pd

In [39]:
people = {
    "First" : ['Himanshu','Rahul','Shyam'],
    "Last"  : ['Kumar','Saini','Singh'],
    "Email" : ['HimanshuKumar@gmail.com','RahulSaini@gmail.com','ShyamSingh@gmail.com']
}

In [40]:
df = pd.DataFrame(people)

In [41]:
df

      First   Last                    Email
0  Himanshu  Kumar  HimanshuKumar@gmail.com
1     Rahul  Saini     RahulSaini@gmail.com
2     Shyam  Singh     ShyamSingh@gmail.com

In [42]:
df['First']+ " " + df['Last']

0    Himanshu Kumar
1       Rahul Saini
2       Shyam Singh
dtype: object

In [43]:
df['Name'] = df['First']+ " " + df['Last']

In [44]:
df

      First   Last                    Email            Name
0  Himanshu  Kumar  HimanshuKumar@gmail.com  Himanshu Kumar
1     Rahul  Saini     RahulSaini@gmail.com     Rahul Saini
2     Shyam  Singh     ShyamSingh@gmail.com     Shyam Singh

In [45]:
df.drop(['First','Last'],axis='columns',inplace=True)

In [46]:
df

                     Email            Name
0  HimanshuKumar@gmail.com  Himanshu Kumar
1     RahulSaini@gmail.com     Rahul Saini
2     ShyamSingh@gmail.com     Shyam Singh

In [47]:
x= df['Name'].str.split(' ',expand=True)

In [48]:
df[['first','last']] = x

In [49]:
df

                     Email            Name     first   last
0  HimanshuKumar@gmail.com  Himanshu Kumar  Himanshu  Kumar
1     RahulSaini@gmail.com     Rahul Saini     Rahul  Saini
2     ShyamSingh@gmail.com     Shyam Singh     Shyam  Singh

how to append a new row of data

In [58]:
new_row = pd.DataFrame({'Email':['tonyStart@gmail.com'],"first":['Tony'],"last":['Start']})

In [60]:
df = pd.concat([df,new_row],ignore_index=True)

In [61]:
df

                     Email            Name     first   last
0  HimanshuKumar@gmail.com  Himanshu Kumar  Himanshu  Kumar
1     RahulSaini@gmail.com     Rahul Saini     Rahul  Saini
2     ShyamSingh@gmail.com     Shyam Singh     Shyam  Singh
3      tonyStart@gmail.com             NaN      Tony  Start